# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CzQcXgo5IU2RwH1FgEbFcJ3yQtnP1-ph
"""

# Install OpenCV
!pip install opencv-python

# Import necessary libraries
from google.colab.patches import cv2_imshow
import cv2

# List of image file paths
image_files = [
    '/content/rasm.png',
    '/content/download.jpeg',
    '/content/download (4).jpeg',
    '/content/download (3).jpeg',
    '/content/download (2).jpeg',
    '/content/download (1).jpeg'
]

# Loop through each file
for file in image_files:
    # Read the image
    image = cv2.imread(file)

    # Check if the image was loaded successfully
    if image is None:
        print(f"Image '{file}' not found or could not be loaded. Skipping...")
        continue

    # Display the original image
    print(f"Displaying original image: {file}")
    cv2_imshow(image)

    # Convert to grayscale
    grayscale = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Display the grayscale image
    print(f"Displaying grayscale image: {file}")
    cv2_imshow(grayscale)